language: ruby
bundler_args: --without development
rvm:
  - '2.0.0'
before_script:
  - psql -c 'create database nikephoros_test;' -U postgres
  - 'bundle exec rake db:migrate'
script: bundle exec rspec spec
