language: ruby
bundler_args: --without development
rvm:
  - '2.0.0'
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export RUBY_GC_MALLOC_LIMIT=90000000
  - export RUBY_FREE_MIN=200000
before_script:
  - psql -c 'create database nikephoros_test;' -U postgres
  - 'bundle exec rake db:migrate'
script: bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: Vfb/yZQn1AyO9gYV/dLB2V3ltxwMJrgr55NvULJALI3thqbK5cQiFvGjVYBMg/aQnAIwY0tWW2LQ2D0rMz4+qJ/dADBuKW63uSddLiNDsVBBYBUYL/pJ1UdmoVAEHIyfja9CoqiKBUlb6TsHNItcrytnA8ehsAYaneZJLgJC5Dc=
  run: 'rake db:migrate'
